config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :update]
  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create]
  root 'static_pages#home'
  get 'invitations', to: "invites#index"
  get 'privacy_policy', to: "static_pages#privacy"
  post 'invitations/accept/:id', to: "invites#accept_invite", as: "accept_invite"
  post 'invitations/decline/:id', to: "invites#decline_invite", as: "decline_invite"
  post 'users/:id/send_request', to: "friends#send_request", as: "send_request"
  get 'users/:id/friends', to: "friends#index", as: "user_friends"
  post 'users/friends/remove/:id', to: "friends#destroy", as: "friend_remove"
  post 'post/:id/liked', to: "posts#liked", as: "post_liked"
  post 'post/:id/unliked', to: "posts#unliked", as: "post_unliked"
  get  'users/:id/liked_posts', to: "posts#liked_posts", as: "liked_posts"
  get  'users/:id/edit_profile', to: "users#edit_profile", as: "edit_profile"
  patch  'users/:id/update_profile', to: "users#update_profile", as: "update_profile"
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def index
  end

  def accept_invite
    user = User.find(params[:id])
    if current_user.requested_friends.include?(user)
      current_user.accept_request(user)
      flash[:success] = "#{user.username} #{t('friends.add')}"
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def decline_invite
    user = User.find(params[:id])
    if current_user.requested_friends.include?(user)
      current_user.decline_request(user)
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/index.html.erb
<section id="invitesIndex" class="pb-4">
  <div class="invites-index__body">
    <div class="invites container">
      <h5><%= t('invites.respond_to') %></h5>
      <p class="pending">
        <a class="" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          <%= t('invites.view_sent') %>
        </a>
      </p>
      <div class="collapse" id="collapseExample">
        <% current_user.pending_friends.each do |request| %>
          <div class="invite">
            <%= link_to request, class: "invite__pp" do %>
              <div class="mx-auto invite-avatar avatar" style="background-image: url('<%= request.avatar_url %>')"></div>
            <% end %>
            <%= link_to request.username, request, class: "invite__username" %>
            <div class="invite__pending"><%= t('invites.waiting') %></div>
          </div>
        <% end %>
      </div>

      <% if current_user.requested_friends.any? %>
        <% current_user.requested_friends.each do |request| %>
          <div class="invite">
            <%= link_to request, class: "invite__pp" do %>
              <div class="mx-auto invite-avatar avatar" style="background-image: url('<%= request.avatar_url %>')"></div>
            <% end %>
            <%= link_to request.username, request, class: "invite__username" %>
            <%= link_to t('invites.confirm'), accept_invite_url(request), method: :post, class: "btn btn-primary" %>
            <%= link_to t('invites.delete_request'), decline_invite_url(request), method: :post, class: "btn btn-decline" %>
          </div>
        <% end %>
      <% else %>
        <div class="no-invites text-center"><%= t('invites.no-invites') %></div>
      <% end %>
    </div>
  </div>
</section>