config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :update]
  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create]
  root 'static_pages#home'
  get 'invitations', to: "invites#index"
  get 'privacy_policy', to: "static_pages#privacy"
  post 'invitations/accept/:id', to: "invites#accept_invite", as: "accept_invite"
  post 'invitations/decline/:id', to: "invites#decline_invite", as: "decline_invite"
  post 'users/:id/send_request', to: "friends#send_request", as: "send_request"
  get 'users/:id/friends', to: "friends#index", as: "user_friends"
  post 'users/friends/remove/:id', to: "friends#destroy", as: "friend_remove"
  post 'post/:id/liked', to: "posts#liked", as: "post_liked"
  post 'post/:id/unliked', to: "posts#unliked", as: "post_unliked"
  get  'users/:id/liked_posts', to: "posts#liked_posts", as: "liked_posts"
  get  'users/:id/edit_profile', to: "users#edit_profile", as: "edit_profile"
  patch  'users/:id/update_profile', to: "users#update_profile", as: "update_profile"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :user_logged_in, except: [:privacy]
  def home
    @post = Post.new
    @comment = Comment.new
    friend_ids = current_user.friend_ids
    @posts = Post.where("user_id IN (?) OR user_id = ?", friend_ids, current_user.id).order(created_at: :desc).paginate(:page => params[:page], :per_page => 7)
  end

  def notifications
  end

  def privacy
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Clonebook") %>

<section id="home" class="">
  <div class="container">

    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key} container" %>
    <% end %>
    <div class="row no-gutters">
      <div class="user-info col-md-3 d-none d-md-block">
        <div class="user-info__cover"></div>
        <div class="text-center">
          <%= link_to current_user do %>
            <div class="mx-auto home-avatar avatar rounded-circle" style="background-image: url('<%= current_user.avatar_url %>')"></div>
          <% end %>
        </div>
        <div class="text-center user-info__username">
          <%= link_to current_user.username, current_user %>
        </div>
        <div class="user-info__stats">
          <div>
            <%= link_to current_user do %>
              <%= t('user-info.posts') %><br />
              <i><%= current_user.posts.count %></i>
            <% end %>
          </div>
          <div>
            <%= link_to user_friends_url(current_user) do %>
              <%= t('user-info.friends') %><br />
              <i><%= current_user.friends.count%></i>
            <% end %>
          </div>
        </div>
      </div>

      <div class="dol-12 col-md-8 ml-auto post__form">
        <div class="d-flex">
          <div class="d-none d-md-block"><div class="post-form-avatar avatar rounded-circle" style="background-image: url('<%= current_user.avatar_url %>')"></div></div>
          <%= form_for(@post) do |f| %>
            <%= f.text_area :body, class: "col-auto form-control",
                                    placeholder: true %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.submit t('home.btn-post'), class: "btn float-right" %>
          <% end %>
        </div>
      </div>
    </div>

    <%= render 'shared/feed' %>
  </div>
</section>

app/views/static_pages/privacy.html.erb
<section id="privacyPolicy" class="py-4">
  <% if params[:locale] == "fr" || params[:locale] == nil %>
    <div class="container">
      <h2>Politique modèle de confidentialité</h2>
      <h5>
        Collecte des renseignements personnels
      </h5>
      <p>
        Nous collectons les renseignements suivants :
      </p>
      <ul>
        <li>Nom d'utilisateur</li>
        <li>Adresse électronique</li>
      </ul>
      <p>
        Les renseignements personnels que nous collectons sont recueillis au
        travers de formulaires et grâce à l'interactivité établie entre vous et
        notre site Web. Nous utilisons également, comme indiqué dans la
        section suivante, des fichiers témoins et/ou journaux pour réunir des
        informations vous concernant.
      </p>
      <h5>
        Formulaires et interactivité:
      </h5>
      <p>
        Vos renseignements personnels sont collectés par le biais de formulaire, à savoir :
      </p>
      <ul>
        <li>Formulaire d'inscription au site Web</li>
      </ul>
      <p>
        Nous utilisons les renseignements ainsi collectés pour les finalités suivantes :
      </p>
      <ul>
        <li>Gestion du site Web (présentation, organisation)</li>
      </ul>
      <p>
        Vos renseignements sont également collectés par le biais de l'interactivité
        pouvant s'établir entre vous et notre site Web et ce, de la façon suivante:
      </p>
      <ul>
        <li>Gestion du site Web (présentation, organisation)</li>
      </ul>
      <p>
        Nous utilisons les renseignements ainsi collectés pour les finalités suivantes :
      </p>
      <ul>
        <li>Aire de discussion</li>
        <li>Commentaires</li>
      </ul>
      <h5>
        Sécurité
      </h5>
      <p>
        Les renseignements personnels que nous collectons sont conservés dans
        un environnement sécurisé. Les personnes travaillant pour nous sont
        tenues de respecter la confidentialité de vos informations.<br />
        Pour assurer la sécurité de vos renseignements personnels, nous avons
        recours aux mesures suivantes :
      </p>
      <ul>
        <li>Protocole SSL (Secure Sockets Layer)</li>
        <li>Gestion des accès - personne autorisée</li>
        <li>Gestion des accès - personne concernée</li>
        <li>Identifiant / mot de passe</li>
      </ul>
    </div>
  <% else %>
    <div class="container">
      <h2>Privacy Policy</h2>
      <p>
        This privacy policy has been compiled to better serve those who are
        concerned with how their 'Personally Identifiable Information' (PII) is
        being used online. PII, as described in US privacy law and information
        security, is information that can be used on its own or with other
        information to identify, contact, or locate a single person, or to identify
        an individual in context. Please read our privacy policy carefully to get a
        clear understanding of how we collect, use, protect or otherwise handle
        your Personally Identifiable Information in accordance with our website.
      </p>
      <h5>
        What personal information do we collect from the people that visit our app?
      </h5>
      <p>
        When registering on our site, as appropriate, you may be
        asked to enter your name, email address or other details to help you with
        your experience.
      </p>
      <h5>
        When do we collect information?
      </h5>
      <p>
        We collect information from you when you register on our site or enter
        information on our site.
      </p>
      <h5>
        How do we use your information?
      </h5>
      <p>
        We may use the information we collect from you when you register, sign up
        for our newsletter, surf the website, or use certain other site features
        in the following ways:
      </p>
      <ul>
        <li>To personalize your experience and to allow us to deliver the type
          of content in which you are most interested.
        </li>
        <li>
          To improve our website in order to better serve you.
        </li>
      </ul>
      <h5>
        How do we protect your information?
      </h5>
      <p>
        We do not use vulnerability scanning and/or scanning to PCI standards.<br />
        We only provide articles and information. We never ask for credit card numbers.<br />
        We do not use Malware Scanning.<br />
        <br />
        Your personal information is contained behind secured networks and is
        only accessible by a limited number of persons who have special access
        rights to such systems, and are required to keep the information confidential.
        In addition, all sensitive/credit information you supply is encrypted
        via Secure Socket Layer (SSL) technology.<br />
        <br />
        We implement a variety of security measures when a user enters, submits,
        or accesses their information to maintain the safety of your personal information.
      </p>
      <h5>
        Do we use 'cookies'?
      </h5>
      <p>
        Yes. Cookies are small files that a site or its service provider
        transfers to your computer's hard drive through your Web browser
        (if you allow) that enables the site's or service provider's systems to
        recognize your browser and capture and remember certain information.
        They are also used to help us understand your preferences based on
        previous or current site activity, which enables us to provide you with
        improved services.
      </p>
      <h5>
        We use cookies to:
      </h5>
      <ul>
        <li>Understand and save user's preferences for future visits.</li>
      </ul>
      <p>
        You can choose to have your computer warn you each time a cookie is being
        sent, or you can choose to turn off all cookies. You do this through your
        browser settings. Since browser is a little different, look at your
        browser's Help Menu to learn the correct way to modify your cookies.
      </p>
      <h5>
        If users disable cookies in their browser:
      </h5>
      <p>
        If you turn cookies off, Some of the features that make your site
        experience more efficient may not function properly.
      </p>
      <h5>
        Third-party disclosure
      </h5>
      <p>
        We do not include or offer third-party products or services on our website.
      </p>
      <h5>
        Third-party links
      </h5>
      <p>
        We do not include or offer third-party products or services on our website.
      </p>
      <h5>
        California Online Privacy Protection Act
      </h5>
      <p>
        CalOPPA is the first state law in the nation to require commercial
        websites and online services to post a privacy policy. The law's reach
        stretches well beyond California to require any person or company in the
        United States (and conceivably the world) that operates websites
        collecting Personally Identifiable Information from California consumers
        to post a conspicuous privacy policy on its website stating exactly the
        information being collected and those individuals or companies with whom
        it is being shared. - See more at:
        http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf
      </p>
      <h5>
        According to CalOPPA, we agree to the following:
      </h5>
      <p>
        Users can visit our site anonymously.<br />
        Once this privacy policy is created, we will add a link to it on our home
        page or as a minimum, on the first significant page after entering our website.<br />
        Our Privacy Policy link includes the word 'Privacy' and can easily be
        found on the page specified above.<br />
        <br />
        You will be notified of any Privacy Policy changes:
      </p>
      <ul>
        <li>On our Privacy Policy Page</li>
      </ul>
      <p>Can change your personal information:</p>
      <ul>
        <li>By logging in to your account</li>
      </ul>
      <h5>
        COPPA (Children Online Privacy Protection Act)
      </h5>
      <p>
        When it comes to the collection of personal information from children
        under the age of 13 years old, the Children's Online Privacy Protection
        Act (COPPA) puts parents in control. The Federal Trade Commission,
        United States' consumer protection agency, enforces the COPPA Rule,
        which spells out what operators of websites and online services must do
        to protect children's privacy and safety online.<br />
        <br />
        We do not specifically market to children under the age of 13 years old.
      </p>
      <h5>
        CAN SPAM Act
      </h5>
      <p>
        The CAN-SPAM Act is a law that sets the rules for commercial email,
        establishes requirements for commercial messages, gives recipients the
        right to have emails stopped from being sent to them, and spells out
        tough penalties for violations.
      </p>
      <h5>
        We collect your email address in order to:
      </h5>
      <ul>
        <li>Send information, respond to inquiries, and/or other requests or questions</li>
      </ul>
      <h5>
        To be in accordance with CANSPAM, we agree to the following:
      </h5>
      <ul>
        <li>Not use false or misleading subjects or email addresses./li>
        <li>Identify the message as an advertisement in some reasonable way.</li>
        <li>Include the physical address of our business or site headquarters./li>
        <li>Monitor third-party email marketing services for compliance, if one is used.</li>
        <li>Honor opt-out/unsubscribe requests quickly.</li>
        <li>Allow users to unsubscribe by using the link at the bottom of each email.</li>
      </ul>
      <h5>
        If at any time you would like to unsubscribe from receiving future
        emails, you can email us at
      </h5>
      <ul>
        <li>Follow the instructions at the bottom of each email and we will
          promptly remove you from ALL correspondence.
        </li>
      </ul>
      <h5>
        Contacting Us
      </h5>
      <p>
        If there are any questions regarding this privacy policy, you may contact
        us using the information below.<br />
        <br />
        https://polar-caverns-15767.herokuapp.com<br />
        support@support.com<br />
        <br />
        Last edited on 2018-03-18
      </p>
    </div>
  <% end %>

</section>