config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :update]
  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create]
  root 'static_pages#home'
  get 'invitations', to: "invites#index"
  get 'privacy_policy', to: "static_pages#privacy"
  post 'invitations/accept/:id', to: "invites#accept_invite", as: "accept_invite"
  post 'invitations/decline/:id', to: "invites#decline_invite", as: "decline_invite"
  post 'users/:id/send_request', to: "friends#send_request", as: "send_request"
  get 'users/:id/friends', to: "friends#index", as: "user_friends"
  post 'users/friends/remove/:id', to: "friends#destroy", as: "friend_remove"
  post 'post/:id/liked', to: "posts#liked", as: "post_liked"
  post 'post/:id/unliked', to: "posts#unliked", as: "post_unliked"
  get  'users/:id/liked_posts', to: "posts#liked_posts", as: "liked_posts"
  get  'users/:id/edit_profile', to: "users#edit_profile", as: "edit_profile"
  patch  'users/:id/update_profile', to: "users#update_profile", as: "update_profile"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  require "faker"
  before_save { generate_avatar }
  acts_as_voter
  include Gravtastic
  gravtastic size: 150
  has_friendship
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true, length: {minimum:6, maximum:30}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  private

  def generate_avatar
    if self.avatar_url.blank?
      self.avatar_url = Faker::Avatar.image("#{SecureRandom.urlsafe_base64}", "150x150", "jpg", "set4", "bg2")
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_logged_in, only: [:show]
  before_action :correct_user, only: [:edit_profile, :update_profile]
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 7)
    @comment = Comment.new
  end

  def edit_profile
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 7)
    @comment = Comment.new
  end

  def update_profile
    user = User.find(params[:id])
    if user.update_attributes(user_params)
      flash[:success] = t('edit-profile.save')
      redirect_to user
    else
      redirect_to edit_profile_url(user)
    end
  end

  def sign
  end

  ## Generate a new avatar
  def update
    user = User.find(params[:id])
    if user.update_attributes(user_params)
      flash[:success] = t('edit-profile.new_avatar')
      redirect_to edit_profile_url(user)
    else
      redirect_to edit_profile_url(user)
    end
end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation,
                                   :bio, :location, :birthday, :avatar_url)
    end

    def correct_user
      user = User.find(params[:id])
      unless current_user == user
        redirect_to root_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  require 'faker'

  # Generate an avatar picture.
  def generate_avatar
    Faker::Avatar.image("#{SecureRandom.urlsafe_base64}", "150x150", "jpg", "set4", "bg2")
  end
end

app/views/users/edit_profile.html.erb
<section id="userEditProfile">
  <%= render 'shared/user_navbar' %>
  <div class="container" id="user-edit-profile__body">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key} container" %>
    <% end %>

    <div class="row no-gutters">
      <div class="user-info col-md-3">

        <%= form_for(@user, url: update_profile_url) do |f| %>
          <%= f.text_field :username, autofocus: true, class: "form-control",
                                      placeholder: true %>
          <%= f.text_field :bio, autofocus: true, class: "form-control",
                                      placeholder: true %>
          <%= f.text_field :location, autofocus: true, class: "form-control",
                                      placeholder: true %>
          <%= f.date_field :birthday, autofocus: true, class: "form-control",
                                      placeholder: true %>
          <div class="text-center">
            <%= f.submit t('edit-profile.update'), class: "btn" %>
          </div>
        <% end %>
        <%= form_for(@user) do |f| %>
          <%= f.hidden_field :avatar_url, value: generate_avatar %>
          <div class="text-center">
            <%= f.submit t('edit-profile.btn-avatar'), class: "btn" %>
          </div>
        <% end %>

      </div>

      <%= render 'shared/feed' %>

  </div>
</section>

app/views/users/show.html.erb
<section id="userShow">
  <%= render 'shared/user_navbar' %>
  <div class="container" id="user-show__body">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key} container" %>
    <% end %>

    <div class="row no-gutters">
      <%= render 'shared/user-info' %>

      <%= render 'shared/feed' %>
    </div>
  </div>
</section>