config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :update]
  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create]
  root 'static_pages#home'
  get 'invitations', to: "invites#index"
  get 'privacy_policy', to: "static_pages#privacy"
  post 'invitations/accept/:id', to: "invites#accept_invite", as: "accept_invite"
  post 'invitations/decline/:id', to: "invites#decline_invite", as: "decline_invite"
  post 'users/:id/send_request', to: "friends#send_request", as: "send_request"
  get 'users/:id/friends', to: "friends#index", as: "user_friends"
  post 'users/friends/remove/:id', to: "friends#destroy", as: "friend_remove"
  post 'post/:id/liked', to: "posts#liked", as: "post_liked"
  post 'post/:id/unliked', to: "posts#unliked", as: "post_unliked"
  get  'users/:id/liked_posts', to: "posts#liked_posts", as: "liked_posts"
  get  'users/:id/edit_profile', to: "users#edit_profile", as: "edit_profile"
  patch  'users/:id/update_profile', to: "users#update_profile", as: "update_profile"
end

app/views/shared/_feed.html.erb
<div class="ml-auto feed">
  <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <% if @posts.any? %>
    <% @posts.each do |post| %>
      <div class="ml-auto post">
        <div class="post__header">
          <%= link_to post.user do %>
            <div class="post-avatar avatar rounded-circle" style="background-image: url('<%= post.user.avatar_url %>')">
            </div>
          <% end %>
          <div>
            <%= link_to post.user.username, post.user,
              class: "post__header__username" %>
            <div class="post__header__posted-at">
              <%= t('home.posted_at') %>
              <%= time_ago_in_words(post.created_at) %>
              <% if params[:locale] == "en" %>
                <span>ago</span>
              <% end %>
            </div>
          </div>
          <% if post.user == current_user %>
            <div class="dropdown show ml-auto post__header__delete">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              </a>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                <%= link_to t('post.delete'), post, class: "ml-auto dropdown-item",
                    method: :delete %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="post__body">
          <%= post.body %>
        </div>
        <div class="post__footer">
          <div>
            <% if post.get_likes.size == 1 %>
              <%= post.get_likes.size %>
              <%= t('post.like') %>
            <% else %>
              <%= post.get_likes.size %>
              <%= t('post.likes') %>
            <% end %>
          </div>
        </div>
        <div class="post__btn">
          <div>
            <% if current_user.voted_as_when_voted_for(post) %>
              <%= link_to post_unliked_path(post), method: :post, remote: true do %>
                <%= fa_icon "heart" %> <%= t('post.unliked') %>
              <% end %>
            <% else %>
              <%= link_to post_liked_path(post), method: :post, remote: true do %>
                <%= fa_icon "heart" %> <%= t('post.liked') %>
              <% end %>
            <% end %>
          </div>
          <div style="color: #898f9c;">
            <%= fa_icon "comment" %> <%= post.comments.count %> <%= t('post.comments') %>
          </div>
        </div>
        <div class="comment-container" id="collapse<%= post.id %>">
          <div class="d-flex">
            <div class="d-none d-md-block">
              <div class="comment-avatar avatar rounded-circle" style="background-image: url('<%= current_user.avatar_url %>')"></div>
            </div>
            <%= form_for(@comment) do |f| %>
              <%= f.text_field :body, placeholder: true, class: "form-control" %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_id, value: post.id %>
              <%= f.submit t('home.btn-post'), class: "btn" %>
            <% end %>
          </div>
          <% post.comments.each do |comment| %>
            <div class="comment">
              <div>
                <div class="comment-avatar avatar rounded-circle" style="background-image: url('<%= comment.user.avatar_url %>')"></div>
              </div>
              <div class="comment__body">
                <div>
                  <%= link_to comment.user.username, comment.user,
                    class: "comment__username" %>
                  <span>&nbsp;<%= comment.body %></span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/shared/_user-info.html.erb
<div class="user-info col-md-3 d-none d-md-block">
  <div class="text-center user-info__username">
    <%= link_to @user.username, @user %>
  </div>
  <% if !@user.bio.blank?%>
    <div class="user-info__bio">
      <%= @user.bio %>
    </div>
  <% end %>
  <table style="width:100%">
    <% if !@user.location.blank? %>
      <tr>
        <td><%= fa_icon "map-marker" %></td>
        <td><%= @user.location %></td>
      </tr>
    <% end %>
    <% if !@user.birthday.blank? %>
      <tr>
        <td><%= fa_icon "birthday-cake" %></td>
        <td><%= t('user-show.birthday') %> <%= l(@user.birthday, format: "%d %B %Y") %></td>
      </tr>
    <% end %>
    <tr>
      <td><%= fa_icon "calendar" %></td>
      <td><%= t('user-show.joined') %> <%= l(@user.created_at, format: "%B %Y") %></td>
    </tr>
  </table>
</div>

app/views/shared/_user_navbar.html.erb
<div id="userNavbarMd" class="d-none d-md-block">
  <div class="user__cover">
    <div class="container">
      <div class="col-10 ml-auto user__username"><%= @user.username %></div>
    </div>
  </div>

  <div class="user__nav-background">
    <div class="user__nav container">
      <nav class="ml-auto col-10">
        <ul class="nav">
          <li class="nav-item <%= 'active' if current_page?(@user) %>">
            <%= link_to @user, class: "nav-link" do %>
              <%= t('user_navbar.posts')%> (<%= @user.posts.count %>)
            <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(user_friends_path) %>">
            <%= link_to user_friends_path, class: "nav-link" do %>
              <%= t('user_navbar.friends') %> (<%= @user.friends.count %>)
            <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(liked_posts_path(@user)) %>">
            <%= link_to liked_posts_path(@user), class: "nav-link" do %>
              <%= t('user_navbar.like') %> (<%= @user.get_voted(Post).count %>)
            <% end %>
          </li>
          <li class="nav-item">
            <% if @user == current_user %>
              <% if current_page?(edit_profile_path(current_user)) %>
                <%= link_to t('user_navbar.cancel'), current_user,
                                                     class: "nav-link user-nav-btn"%>
              <% else %>
                <%= link_to t('user_navbar.edit'), edit_profile_path(current_user),
                                                  class: "nav-link user-nav-btn" %>
              <% end %>
            <% else %>
              <% if current_user.friends_with?(@user) %>
                <%= link_to t('user_navbar.unfriend'), friend_remove_path(@user),
                                              method: :post,
                                              class: "nav-link user-nav-btn" %>
              <% elsif @user.pending_friends.include?(current_user) %>
                <%= link_to t('user_navbar.respond_to'), invitations_path,
                                              class: "nav-link user-nav-btn" %>
              <% else %>
                <% if current_user.pending_friends.include?(@user) %>
                  <span class="nav-link user-nav-btn"><%= t('user_navbar.friend_request_sent') %></span>
                <% else %>
                  <%= link_to t('user_navbar.add_friend'), send_request_path,
                                                          method: :post,
                                                          class: "nav-link user-nav-btn" %>
                <% end %>
              <% end %>
            <% end %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
  <div class="container">
    <div class="user__pp col-2">
      <% if @user.avatar_url.blank? %>
        <%= image_tag @user.gravatar_url, class: "avatar w-100" %>
      <% else %>
        <div class="avatar rounded-circle" style="background-image: url('<%= @user.avatar_url %>')">
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id="userNavbarXs" class="d-md-none">

  <div class="user__cover">
  </div>
  <div class="text-center user__pp-container">
    <div class="user_pp text-center d-inline-block">
      <div class="avatar rounded-circle" style="background-image: url('<%= @user.avatar_url %>')">
      </div>
      <div class="user__username"><%= @user.username %></div>
    </div>
  </div>

  <div class="user-info__xs">
    <% if !@user.bio.blank?%>
      <div class="user-info__bio">
        <%= @user.bio %>
      </div>
    <% end %>
    <table style="width:100%">
      <% if !@user.location.blank? %>
        <tr>
          <td><%= fa_icon "map-marker" %></td>
          <td><%= @user.location %></td>
        </tr>
      <% end %>
      <% if !@user.birthday.blank? %>
        <tr>
          <td><%= fa_icon "birthday-cake" %></td>
          <td><%= t('user-show.birthday') %> <%= l(@user.birthday, format: "%d %B %Y") %></td>
        </tr>
      <% end %>
      <tr>
        <td><%= fa_icon "calendar" %></td>
        <td><%= t('user-show.joined') %> <%= l(@user.created_at, format: "%B %Y") %></td>
      </tr>
    </table>
  </div>

  <div class="dropdown show">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <% if current_page?(@user) %>
        <%= t('user_navbar.posts') %>
      <% elsif current_page?(user_friends_path) %>
        <%= t('user_navbar.friends') %>
      <% elsif current_page?(liked_posts_path(@user)) %>
        <%= t('user_navbar.like') %>
      <% elsif current_page?(edit_profile_path(@user)) %>
        <%= t('user_navbar.edit') %>
      <% end %>
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <%= link_to @user, class: "dropdown-item" do %>
        <%= t('user_navbar.posts')%> (<%= @user.posts.count %>)
      <% end %>
      <div class="dropdown-divider"></div>
      <%= link_to user_friends_path, class: "dropdown-item" do %>
        <%= t('user_navbar.friends') %> (<%= @user.friends.count %>)
      <% end %>
      <div class="dropdown-divider"></div>
      <%= link_to liked_posts_path(@user), class: "dropdown-item" do %>
        <%= t('user_navbar.like') %> (<%= @user.get_voted(Post).count %>)
      <% end %>
      <div class="dropdown-divider"></div>
      <div class="text-center">
        <% if @user == current_user %>
          <% if current_page?(edit_profile_path(current_user)) %>
            <%= link_to t('user_navbar.cancel'), current_user,
                                                  class: "user-nav-btn"%>
          <% else %>
            <%= link_to t('user_navbar.edit'), edit_profile_path(current_user),
                                              class: "user-nav-btn" %>
          <% end %>
        <% else %>
          <% if current_user.friends_with?(@user) %>
            <%= link_to "Remove Friend", friend_remove_path(@user),
                                          method: :post,
                                          class: "user-nav-btn" %>
          <% else %>
            <% if current_user.pending_friends.include?(@user) %>
              <span class="user-nav-btn"><%= t('user_navbar.friend_request_sent') %></span>
            <% else %>
              <%= link_to t('user_navbar.add_friend'), send_request_path,
                                                        method: :post,
                                                        class: "user-nav-btn" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>